sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mikharaev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mikharaev/docker-react npm run test